increasing Brightness

In [1]:
import cv2
import numpy as np

In [2]:
image=cv2.imread("C:/Users/Raya-Center/Pictures/Saved Pictures/download.jpg")

In [3]:
M=np.ones(image.shape,dtype="uint8")*50

In [4]:
print(M)

[[[50 50 50]
  [50 50 50]
  [50 50 50]
  ...
  [50 50 50]
  [50 50 50]
  [50 50 50]]

 [[50 50 50]
  [50 50 50]
  [50 50 50]
  ...
  [50 50 50]
  [50 50 50]
  [50 50 50]]

 [[50 50 50]
  [50 50 50]
  [50 50 50]
  ...
  [50 50 50]
  [50 50 50]
  [50 50 50]]

 ...

 [[50 50 50]
  [50 50 50]
  [50 50 50]
  ...
  [50 50 50]
  [50 50 50]
  [50 50 50]]

 [[50 50 50]
  [50 50 50]
  [50 50 50]
  ...
  [50 50 50]
  [50 50 50]
  [50 50 50]]

 [[50 50 50]
  [50 50 50]
  [50 50 50]
  ...
  [50 50 50]
  [50 50 50]
  [50 50 50]]]


In [5]:
added=cv2.add(image,M)
cv2.imshow("my pic",added)
cv2.waitKey(0)
cv2.destroyAllWindows()

subtract

In [6]:
M=np.ones(image.shape,dtype="uint8")*60

In [8]:
subtracts=cv2.subtract(image,M)
cv2.imshow("my pic",subtracts)
cv2.waitKey(0)
cv2.destroyAllWindows()